In [1]:
import pandas as pd
pd.set_option("display.max_columns", 500)
pd.set_option("display.max_rows", 500)

## Table description generation

Enter the following info: 
 - Table name
 - Location
 - Separator
 - Encoding (optional)
 - Decimal mark (optional)

In [2]:
table = "VIGABT_POLIZAS.tsv"
location = "../../data/raw"
sep = '\t'
encoding = 'latin1'
decimal = ','

### Make a first view of the dataset to check most interesting columns

**Run this if it's a big file**

In [3]:
for chunk in pd.read_csv(f"{location}/{table}",
                         sep=sep,
                         encoding=encoding,
                         decimal=decimal,
                         chunksize=1000000):
    df = chunk
    break

/home/voolkia/anaconda3/envs/test/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (13,18,25,27,28,37,43,49,50,57,58,59,62,63,64,67,68,69,70,71,72) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

**Run this if it's a relatively small file**

In [3]:
df = pd.read_csv(f"{location}/{table}",
                sep=sep,
                encoding=encoding,
                decimal=decimal)

In [4]:
df.head(15)

,NUM_SECU_POL,COD_ZONA_RC,COD_ZONA_ROBO,NUM_POL1,COD_AGENCIA_EMISORA,NUM_POL_ANT,RENOVADA_POR,COD_CIA,COD_SECC,COD_RAMO,FECHA_VIG_POL,FECHA_VENC_POL,COD_PLAN,MCA_INDIVIDUO_AGRUPADO,CIF_ID_EMPRESA,PORC_DESCUENTO,COD_PROD,COD_COBRO,POLIZA_AL_50,ESTADO_CIVIL_ASEGURADO,COD_POSTAL,IMP_BONIFICACION_MES,IMP_PREMIO_MES,IMP_PRIMA_FACT_MES,FECHA_PROCESO,MCA_MOVIMIENTO,MCA_VIGENCIA,MCA_BAJA,COD_COBRO_ANTERIOR,FECHA_VIG_ORIG_POL,MCA_AGRAVANTE,MCA_EMPLEADO,COD_AGENCIA_PRESU,COD_AGENCIA_SOLIC,COD_AGENCIA_EMI,COD_AGENCIA,COD_AGENCIA_PROD,ALTA_REAL,COD_INICIADOR,CAPITAL_VEHICULO,CAPITAL_ACCESORIOS,CAPITAL_ASEGURADO_COTIZACION,COD_RIES,NRO_SOLIC_EXTERNA,ANTIGUEDAD,ANTIGUEDAD_TRADELTA,MCA_CENTRALIZADA,MCA_VENCIDA,IMP_BONIFICACION_A_MES,PRENDARIO,NEGOCIO,AGRUPADOR_DIRECTO,COD_AGENCIA_GES,NUM_POL_ORI,MCA_POLIZA_VIP,FECHA_EMI,CANT_RENOVACION,CLIENTE_PERDIDO,CLIENTE_PERDIDO_60,CLIENTE_PERDIDO_90,FECHA_ANTIG,ANTIG,FECHA_VIG_POL_NPO,SEGMENTO,SEGMENTO_2,COD_ZONA_CASCO,PROXIMA_FECHA_RENOV,NEGOCIO_DESC,CLIENTE_PERDIDO_SECC,CLIENTE_PERDIDO_SECC_60,CLIENTE_PERDIDO_SECC_90,TIPO_BAJA,COD_SITUACION,ULTIMA_COD_SITUACION,CIF_ID,SEGMENTO_CLIENTE
0,1754486179999,1,1,5450048179903,5450,5450048179902,5450048179904,1,4,1,28/01/2018,28/02/2018,920,NaN,NaN,NaN,5450,CC,NaN,SO,1708007,0.00,1339.99,1074.76,31/01/2018,NaN,S,NaN,CC,28/11/2017,S,N,6090.0,6090,5450,5450,5450.0,NaN,NaN,87600.0,1080.0,87600.0,1,NaN,64.0,NaN,NaN,NaN,NaN,N,DEF,NaN,NaN,5450048179901,N,28/11/2017,3,NaN,NaN,NaN,28/11/2017,61.0,28/11/2017,MEDIO,MEDIO,1,28/02/2018,Mostrador,NaN,NaN,NaN,NaN,CT,NaN,19264733.0,1
1,1754487779999,1,2,6010037470403,6010,6010037470402,6010037470404,1,4,1,28/01/2018,28/02/2018,967,NaN,NaN,NaN,6010,TM,NaN,SO,1878000,-0.10,2051.19,1931.08,31/01/2018,NaN,S,NaN,TM,28/11/2017,S,N,5660.0,20,6010,6010,6010.0,NaN,NaN,221400.0,1080.0,226800.0,1,NaN,1107.0,NaN,NaN,NaN,-289.66,N,DEF,NaN,5775.0,6010037470401,S,28/11/2017,3,NaN,NaN,NaN,20/01/2015,1104.0,28/11/2017,ALTO,ALTO,1,31/05/2018,Mostrador,NaN,NaN,NaN,NaN,CT,NaN,20526578.0,1
2,1754488299999,1,4,6040052855502,6040,6040052855501,6040052855503,1,4,1,28/12/2017,28/01/2018,954,NaN,NaN,NaN,26066,BA,NaN,SO,1665001,0.00,2699.54,2165.20,31/01/2018,NaN,NaN,S,BA,28/11/2017,S,N,5775.0,3402,6040,6040,3402.0,NaN,72426.0,342300.0,1080.0,342300.0,1,NaN,NaN,NaN,NaN,NaN,NaN,N,DEF,NaN,5775.0,6040052855501,S,28/11/2017,2,S,NaN,NaN,26/09/2017,93.0,28/11/2017,ALTO,ALTO,1,28/02/2018,Mostrador,S,NaN,NaN,A,NaN,NaN,22162468.0,1
3,1754488439999,3,10,5170025278501,5170,0,5170025278502,1,4,1,04/12/2017,04/01/2018,961,NaN,NaN,NaN,5170,BA,NaN,SO,9000010,-0.40,667.39,535.29,31/01/2018,NaN,NaN,S,BA,04/12/2017,S,N,5170.0,5170,5170,5170,5170.0,NaN,NaN,122000.0,250.0,122000.0,1,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,5170025278501,S,28/11/2017,1,S,S,S,04/05/2011,2406.0,04/12/2017,MALTO,MALTO,2,04/03/2018,NaN,S,S,S,A,NaN,NaN,17484524.0,2
4,1754488459999,8,7,6130013104203,6130,6130013104202,6130013104204,1,4,1,27/01/2018,27/02/2018,961,NaN,NaN,NaN,29136,BA,NaN,NaN,5000052,0.00,731.83,691.64,31/01/2018,NaN,S,NaN,BA,27/11/2017,S,N,5775.0,3402,6280,6130,3402.0,NaN,72026.0,200800.0,1080.0,199800.0,1,NaN,NaN,NaN,NaN,NaN,-103.75,N,DEF,NaN,5775.0,6130013104201,S,28/11/2017,3,NaN,NaN,NaN,15/10/2015,835.0,27/11/2017,ALTO,MALTO,2,27/05/2018,Mostrador,NaN,NaN,NaN,NaN,CT,NaN,20964285.0,1
5,1754488699999,6,9,5030014123103,5030,5030014123102,5030014123104,1,4,1,28/01/2018,28/02/2018,961,NaN,NaN,NaN,5030,TM,NaN,SO,3000022,-0.39,667.47,534.41,31/01/2018,NaN,S,NaN,TM,28/11/2017,S,N,5030.0,5030,5030,5030,5030.0,NaN,NaN,71200.0,250.0,71200.0,1,NaN,64.0,NaN,NaN,NaN,NaN,N,DEF,NaN,NaN,5030014123101,S,28/11/2017,3,NaN,NaN,NaN,28/11/2017,61.0,28/11/2017,MEDIO,MEDIO,2,31/05/2018,Mostrador,NaN,NaN,NaN,NaN,CT,NaN,22299320.0,1
6,1754489119999,30,30,5250008795301,5250,0,0,1,4,1,28/11/2017,30/05/2018,921,NaN,NaN,NaN,72038,PP,NaN,SO,5713009,0.00,848.53,685.40,31/01/2018,NaN,S,NaN,PP,28/11/2017,S,N,3401.0,3401,5000,5250,3401.0,NaN,72038.0,180300.0,1080.0,180300.0,1,998000001783231,64.0,NaN,NaN,NaN,NaN,S,PP,NaN,NaN,5250008795301,N,28/11/2017,1,NaN,NaN,NaN,28/11/2017,0.0,28/11/2017,MALTO,MALTO,11,30/05/2018,Prendarios,NaN,NaN,NaN,NaN,CT,NaN,22301012.0,2
7,1754489249999,1,1,5400042562902,5400,5400042562901,5400042562903,1,4,1,01/01/2018,01/02/2018,977,NaN,NaN,NaN,5400,TM,NaN,CA,1824000,-0.14,2090.04,1967.66,31/01/2018,NaN,S,NaN,TM,01/12/2017,S,N,5400.0,5400,5400,5400,5400.0,NaN,NaN,286200.0,1080.0,286200.0,1,NaN,422.0,NaN,NaN,NaN,-295.15,N,DEF,NaN,NaN,5400042562901,S,28/11/2017,2,NaN,NaN,NaN,05/12/2016,392.0,01/12/2017,ALTO,ALTO,1,01/02/2018,Mostrador,NaN,NaN,NaN,NaN,CT,NaN,21511395.0,2
8,1754483839999,1,4,6040052855203,6040,6040052855202,6040052855204,1,4,1,28/01/2018,28/02/2018,942,NaN,NaN,NaN,5660,TM,NaN,UN,1663015,0.00,1398.81,1316.89,31/01/2018,NaN,S,NaN,TM,28/11/2017,S,N,5660.0,5660,6990,6040,5660.0,NaN,NaN,199800.0,1080.0,199800.0,1,NaN,64.0,NaN,NaN,NaN,-197.53,N,DEF,NaN,NaN,6040052855201,S,28/11/2017,3,NaN,NaN,NaN,17/11/2015,803.0,28/11/2017,ALTO,MALTO,1,31/05/2018,Mostrador,NaN,NaN,NaN,NaN,CT,NaN,21015956.0,2
9,1754483869999,6,9,6130013104103,6130,6130013104102,6130013104104,1,4,1,28/01/2018,28/02/2018,942,NaN,NaN,NaN,72029,TM,NaN,DI,5111003,0.00,965.92,912.87,31/01/2018,NaN,S,NaN,TM,28/11/2017,S,N,6130.0,3402,6130,6130,3402.0,NaN,72025.0,317200.0,1080.0,291600.0,1,NaN,6698.0,NaN,NaN,NaN,-136.93,N,DEF,NaN,NaN,6130013104101,S,28/11/2017,3,NaN,NaN,NaN,08/04/1998,7235.0,28/11/2017,ALTO,ALTO,2,31/05/2018,Mostrador,NaN,NaN,NaN,NaN,CT,NaN,1536059.0,2
10,1754484149999,4,9,5110017786101,5110,0,0,1,4,1,28/11/2017,10/06/2018,921,NaN,NaN,NaN,72038,PP,NaN,SO,4000028,0.00,1435.32,1146.42,31/01/2018,NaN,S,NaN,PP,28/11/2017,S,N,3401.0,3401,5734,5110,3401.0,NaN,72038.0,544800.0,1080.0,514000.0,1,998000001783206,64.0,NaN,NaN,NaN,NaN,S,PP,NaN,NaN,5110017786101,N,28/11/2017,1,NaN,NaN,NaN,28/11/2017,0.0,28/11/2017,ALTO,ALTO,2,10/06/2018,Prendarios,NaN,NaN,NaN,NaN,CT,NaN,22301002.0,2
11,1754484699999,1,4,6040052855401,6040,0,0,1,4,1,28/11/2017,20/05/2018,909,NaN,NaN,NaN,72038,PP,NaN,SO,1665001,0.00,1908.25,1530.54,31/01/2018,NaN,S,NaN,PP,28/11/2017,S,N,3401.0,3401,5000,6040,3401.0,NaN,72038.0,279100.0,1080.0,263500.0,1,998000001783212,64.0,NaN,NaN,NaN,NaN,S,PP,NaN,NaN,6040052855401,N,28/11/2017,1,NaN,NaN,NaN,28/11/2017,0.0,28/11/2017,ALTO,ALTO,1,20/05/2018,Prendarios,NaN,NaN,NaN,NaN,CT,NaN,22301003.0,2
12,1754485039999,6,11,5070015489101,5070,0,0,1,4,1,28/11/2017,05/06/2018,921,NaN,NaN,NaN,72038,PP,NaN,CA,3100002,0.00,572.41,460.02,31/01/2018,NaN,S,NaN,PP,28/11/2017,S,N,3401.0,3401,5000,5070,3401.0,NaN,72038.0,203000.0,1080.0,203000.0,1,998000001783201,64.0,NaN,NaN,NaN,NaN,S,PP,NaN,NaN,5070015489101,N,28/11/2017,1,NaN,NaN,NaN,28/11/2017,0.0,28/11/2017,MALTO,MALTO,2,05/06/2018,Prendarios,NaN,NaN,NaN,NaN,CT,NaN,18353179.0,2
13,1754485139999,9,18,5490015047402,5490,5490015047401,0,1,4,1,31/12/2017,31/01/2018,942,NaN,NaN,NaN,5490,TM,NaN,DI,7600002,0.00,1082.03,867.85,31/01/2018,NaN,NaN,S,TM,30/11/2017,S,N,5490.0,5490,5490,5490,5490.0,NaN,NaN,145800.0,8080.0,145800.0,1,NaN,NaN,NaN,NaN,NaN,NaN,N,DEF,NaN,NaN,5490015047401,S,28/11/2017,2,NaN,NaN,NaN,18/04/2006,4275.0,30/11/2017,MEDIO,MEDIO,2,NaN,Mostrador,NaN,NaN,NaN,M,NaN,NaN,12855148.0,2
14,1754485629999,1,1,6190014909903,6190,6190014909902,6190014909904,1,4,1,28/01/2018,28/02/2018,921,NaN,NaN,NaN,6190,TM,NaN,SO,1824002,0.00,1299.96,1156.83,31/01/2018,NaN,S,NaN,TM,28/11/2017,S,N,5660.0,5660,6190,6190,6190.0,NaN,NaN,218100.0,1080.0,206200.0,1,NaN,1140.0,NaN,NaN,NaN,-115.68,N,DEF,NaN,NaN,6190014909901,N,28/11/2017,3,NaN,NaN,NaN,09/08/2012,1998.0,28/11/2017,MALTO,MALTO,1,31/05/2018,Mostrador,NaN,NaN,NaN,NaN,CT,NaN,10766812.0,2

In [5]:
df.dtypes

NUM_SECU_POL                      int64
COD_ZONA_RC                       int64
COD_ZONA_ROBO                     int64
NUM_POL1                          int64
COD_AGENCIA_EMISORA               int64
NUM_POL_ANT                       int64
RENOVADA_POR                      int64
COD_CIA                           int64
COD_SECC                          int64
COD_RAMO                          int64
FECHA_VIG_POL                    object
FECHA_VENC_POL                   object
COD_PLAN                          int64
MCA_INDIVIDUO_AGRUPADO           object
CIF_ID_EMPRESA                  float64
PORC_DESCUENTO                  float64
COD_PROD                          int64
COD_COBRO                        object
POLIZA_AL_50                     object
ESTADO_CIVIL_ASEGURADO           object
COD_POSTAL                        int64
IMP_BONIFICACION_MES            float64
IMP_PREMIO_MES                  float64
IMP_PRIMA_FACT_MES              float64
FECHA_PROCESO                    object
MCA_MOVIMIENTO                   object
MCA_VIGENCIA                     object
MCA_BAJA                         object
COD_COBRO_ANTERIOR               object
FECHA_VIG_ORIG_POL               object
MCA_AGRAVANTE                    object
MCA_EMPLEADO                     object
COD_AGENCIA_PRESU               float64
COD_AGENCIA_SOLIC                 int64
COD_AGENCIA_EMI                   int64
COD_AGENCIA                       int64
COD_AGENCIA_PROD                float64
ALTA_REAL                        object
COD_INICIADOR                   float64
CAPITAL_VEHICULO                float64
CAPITAL_ACCESORIOS              float64
CAPITAL_ASEGURADO_COTIZACION    float64
COD_RIES                          int64
NRO_SOLIC_EXTERNA                object
ANTIGUEDAD                      float64
ANTIGUEDAD_TRADELTA             float64
MCA_CENTRALIZADA                float64
MCA_VENCIDA                     float64
IMP_BONIFICACION_A_MES          float64
PRENDARIO                        object
NEGOCIO                          object
AGRUPADOR_DIRECTO               float64
COD_AGENCIA_GES                 float64
NUM_POL_ORI                       int64
MCA_POLIZA_VIP                   object
FECHA_EMI                        object
CANT_RENOVACION                   int64
CLIENTE_PERDIDO                  object
CLIENTE_PERDIDO_60               object
CLIENTE_PERDIDO_90               object
FECHA_ANTIG                      object
ANTIG                           float64
FECHA_VIG_POL_NPO                object
SEGMENTO                         object
SEGMENTO_2                       object
COD_ZONA_CASCO                    int64
PROXIMA_FECHA_RENOV              object
NEGOCIO_DESC                     object
CLIENTE_PERDIDO_SECC             object
CLIENTE_PERDIDO_SECC_60          object
CLIENTE_PERDIDO_SECC_90          object
TIPO_BAJA                        object
COD_SITUACION                    object
ULTIMA_COD_SITUACION            float64
CIF_ID                          float64
SEGMENTO_CLIENTE                  int64
dtype: object

In [6]:
df.columns

Index(['NUM_SECU_POL', 'COD_ZONA_RC', 'COD_ZONA_ROBO', 'NUM_POL1',
       'COD_AGENCIA_EMISORA', 'NUM_POL_ANT', 'RENOVADA_POR', 'COD_CIA',
       'COD_SECC', 'COD_RAMO', 'FECHA_VIG_POL', 'FECHA_VENC_POL', 'COD_PLAN',
       'MCA_INDIVIDUO_AGRUPADO', 'CIF_ID_EMPRESA', 'PORC_DESCUENTO',
       'COD_PROD', 'COD_COBRO', 'POLIZA_AL_50', 'ESTADO_CIVIL_ASEGURADO',
       'COD_POSTAL', 'IMP_BONIFICACION_MES', 'IMP_PREMIO_MES',
       'IMP_PRIMA_FACT_MES', 'FECHA_PROCESO', 'MCA_MOVIMIENTO', 'MCA_VIGENCIA',
       'MCA_BAJA', 'COD_COBRO_ANTERIOR', 'FECHA_VIG_ORIG_POL', 'MCA_AGRAVANTE',
       'MCA_EMPLEADO', 'COD_AGENCIA_PRESU', 'COD_AGENCIA_SOLIC',
       'COD_AGENCIA_EMI', 'COD_AGENCIA', 'COD_AGENCIA_PROD', 'ALTA_REAL',
       'COD_INICIADOR', 'CAPITAL_VEHICULO', 'CAPITAL_ACCESORIOS',
       'CAPITAL_ASEGURADO_COTIZACION', 'COD_RIES', 'NRO_SOLIC_EXTERNA',
       'ANTIGUEDAD', 'ANTIGUEDAD_TRADELTA', 'MCA_CENTRALIZADA', 'MCA_VENCIDA',
       'IMP_BONIFICACION_A_MES', 'PRENDARIO', 'NEGOCIO', 'AGRUPADOR_DIRECTO',
       'COD_AGENCIA_GES', 'NUM_POL_ORI', 'MCA_POLIZA_VIP', 'FECHA_EMI',
       'CANT_RENOVACION', 'CLIENTE_PERDIDO', 'CLIENTE_PERDIDO_60',
       'CLIENTE_PERDIDO_90', 'FECHA_ANTIG', 'ANTIG', 'FECHA_VIG_POL_NPO',
       'SEGMENTO', 'SEGMENTO_2', 'COD_ZONA_CASCO', 'PROXIMA_FECHA_RENOV',
       'NEGOCIO_DESC', 'CLIENTE_PERDIDO_SECC', 'CLIENTE_PERDIDO_SECC_60',
       'CLIENTE_PERDIDO_SECC_90', 'TIPO_BAJA', 'COD_SITUACION',
       'ULTIMA_COD_SITUACION', 'CIF_ID', 'SEGMENTO_CLIENTE'],
      dtype='object')

*Based on last output, fill this list to mark most relevant columns*

In [3]:
to_use = ['NUM_SECU_POL', 'COD_ZONA_RC', 'COD_ZONA_ROBO', 'NUM_POL1',
       'COD_AGENCIA_EMISORA', 'NUM_POL_ANT', 'RENOVADA_POR', 'COD_CIA',
       'COD_SECC', 'COD_RAMO', 'FECHA_VIG_POL', 'FECHA_VENC_POL', 'COD_PLAN',
       'MCA_INDIVIDUO_AGRUPADO', 'CIF_ID_EMPRESA', 'PORC_DESCUENTO',
       'COD_PROD', 'COD_COBRO', 'POLIZA_AL_50', 'ESTADO_CIVIL_ASEGURADO',
       'COD_POSTAL', 'IMP_BONIFICACION_MES', 'IMP_PREMIO_MES',
       'IMP_PRIMA_FACT_MES', 'FECHA_PROCESO', 'MCA_MOVIMIENTO', 'MCA_VIGENCIA',
       'MCA_BAJA', 'COD_COBRO_ANTERIOR', 'FECHA_VIG_ORIG_POL', 'MCA_AGRAVANTE',
       'MCA_EMPLEADO', 'COD_AGENCIA_PRESU', 'COD_AGENCIA_SOLIC',
       'COD_AGENCIA_EMI', 'COD_AGENCIA', 'COD_AGENCIA_PROD', 'ALTA_REAL',
       'COD_INICIADOR', 'CAPITAL_VEHICULO', 'CAPITAL_ACCESORIOS',
       'CAPITAL_ASEGURADO_COTIZACION', 'COD_RIES', 'NRO_SOLIC_EXTERNA',
       'ANTIGUEDAD', 'ANTIGUEDAD_TRADELTA', 'MCA_CENTRALIZADA', 'MCA_VENCIDA',
       'IMP_BONIFICACION_A_MES', 'PRENDARIO', 'NEGOCIO', 'AGRUPADOR_DIRECTO',
       'COD_AGENCIA_GES', 'NUM_POL_ORI', 'MCA_POLIZA_VIP', 'FECHA_EMI',
       'CANT_RENOVACION', 'FECHA_ANTIG', 'ANTIG', 'FECHA_VIG_POL_NPO',
       'SEGMENTO', 'SEGMENTO_2', 'COD_ZONA_CASCO', 'PROXIMA_FECHA_RENOV',
       'NEGOCIO_DESC', 'TIPO_BAJA', 'COD_SITUACION',
       'ULTIMA_COD_SITUACION', 'CIF_ID', 'SEGMENTO_CLIENTE']

### Now write the file

**If it was a big file, read it completely with this line**

In [ ]:
chunks = pd.read_csv(f"{location}/{table}",
                         sep=sep,
                         encoding=encoding,
                         decimal=decimal,
                         chunksize=1000000,
                         usecols=to_use)
df = pd.concat(chunks)

/home/voolkia/anaconda3/envs/test/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3267: DtypeWarning: Columns (13,18,25,27,28,37,43,49,50,62,63,64,67,71,72) have mixed types. Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [15]:
df["FECHA_EQUIPO"].value_counts().head().to_string()

'06/04/2019    283655\n06/03/2019    239644\n06/05/2019    234558\n05/03/2019    233488\n01/04/2019    197252'

In [21]:
f = open(f'../../docs/{table} feature description.csv','w')
f.write('Column;Used;Null Rate; Type; Unique values; Values\n')
for column in df.columns:
    
    null_rate = round(df[column].isna().mean()*100,2)
    
    unique_vals = df[column].nunique()
    
    if (column in to_use) and null_rate < .5 and unique_vals > 1:
        used = 'X'
    else:
        used=''
    
    dtype = df[column].dtype
    
    if(dtype == 'object'):
        values = f"Top 10:\n{df[column].value_counts(dropna=False).head(10).to_string()}"
    else:
        values = f'[{df[column].min()};{df[column].max()}]'
        
    f.write(f'{column};{used};{null_rate};{dtype};{unique_vals};"{values}"\n')
    
f.close()