In [1]:
import pandas as pd

## Armado de dataset para entrenamiento del modelo

Se usan ventanas de tiempo de 6 meses para agrupar los datos y predecir la baja

In [ ]:
df = pd.read_feather('../../../data/processed/merged_data_18_periods.feather')

In [ ]:
df

In [9]:
import re

In [10]:
periodic_cols = set([''.join([s for s in col if not s.isdigit()]) for col in df[[col for col in df.columns if re.search(f'\d', col)]].columns])

In [ ]:
periodic_cols

In [12]:
df[[col for col in df.columns if re.search(f'_[1-6]$|^[1-6]_', col)]].columns

Index(['1_TIPOINT_A', '1_TIPOINT_I', '1_TIPOINT_O', '2_TIPOINT_A',
       '2_TIPOINT_I', '2_TIPOINT_O', '3_TIPOINT_A', '3_TIPOINT_I',
       '3_TIPOINT_O', '4_TIPOINT_A', '4_TIPOINT_I', '4_TIPOINT_O',
       '5_TIPOINT_A', '5_TIPOINT_I', '5_TIPOINT_O', '6_TIPOINT_A',
       '6_TIPOINT_I', '6_TIPOINT_O', '1_SITUACION_AM', '1_SITUACION_CT',
       '1_SITUACION_EP', '2_SITUACION_AM', '2_SITUACION_CT', '2_SITUACION_EP',
       '3_SITUACION_AM', '3_SITUACION_CT', '3_SITUACION_EP', '4_SITUACION_AM',
       '4_SITUACION_CT', '4_SITUACION_EP', '4_SITUACION_PP', '5_SITUACION_AM',
       '5_SITUACION_CT', '5_SITUACION_EP', '5_SITUACION_PP', '6_SITUACION_AM',
       '6_SITUACION_CT', '6_SITUACION_EP', '6_SITUACION_PP', '1_COBRO_BA',
       '1_COBRO_CC', '1_COBRO_PP', '1_COBRO_SJ', '1_COBRO_TA', '2_COBRO_BA',
       '2_COBRO_CC', '2_COBRO_PP', '2_COBRO_SJ', '2_COBRO_TA', '3_COBRO_BA',
       '3_COBRO_CC', '3_COBRO_PP', '3_COBRO_SJ', '3_COBRO_TA', '4_COBRO_BA',
       '4_COBRO_CC', '4_COBRO_PP', '4_COBRO_SJ', '4_COBRO_TA', '5_COBRO_BA',
       '5_COBRO_CC', '5_COBRO_PP', '5_COBRO_SJ', '5_COBRO_TA', '6_COBRO_BA',
       '6_COBRO_CC', '6_COBRO_PP', '6_COBRO_SJ', '6_COBRO_TA', 'MONTO_PAGO_1',
       'MONTO_PAGO_2', 'MONTO_PAGO_3', 'MONTO_PAGO_4', 'MONTO_PAGO_5',
       'MONTO_PAGO_6', 'demora_pago_1', 'demora_pago_2', 'demora_pago_3',
       'demora_pago_4', 'demora_pago_5', 'demora_pago_6'],
      dtype='object')

**Prueba para primer recorte** 
- Periodos 1 a 6

**Removemos todas las columnas temporales y las guardamos aparte**

In [13]:
grouped_df = df[[col for col in df.columns if not any(char.isdigit() for char in col)]]

In [14]:
grouped_df

,CIF_ID,hist_polizas,periodo_baja,ORIGEN,SEXO,TIPO_PERSONA,CLIENTE,ANO_DE_NACIMIENTO,FECHA_NACIMIENTO,ESTADO_CIVIL,DATECO_TRABAJA,DATECO_AUTONOMO,DATECO_RAZON_SOCIAL_EMPLEADOR,DATMAR_COMPLETO_ESTUDIOS,DATMAR_NIVEL_EDUCACION,POSICION_IVA
0,571.0,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,082,M,F,None,1973.0,28/06/1973,Soltero,None,None,None,None,None,5.0
1,573.0,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,082,M,F,None,1941.0,22/01/1941,Soltero,None,None,None,None,None,5.0
2,1009.0,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,082,M,F,None,NaN,None,None,None,None,None,None,None,5.0
3,1103.0,3 3 3 3 3 1 1 1 0 1 1 1 1 1 1 1 1 1,-1,082,M,F,None,1938.0,13/05/1938,Soltero,None,None,None,None,None,5.0
4,1313.0,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,082,M,F,None,1953.0,26/10/1953,Casado,None,None,None,None,None,5.0
5,1429.0,2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0,16,082,M,F,None,1968.0,10/05/1968,Casado,None,None,None,None,None,5.0
6,1482.0,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,082,M,F,None,1954.0,11/10/1954,Soltero,None,None,None,None,None,5.0
7,1559.0,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,082,M,F,None,1956.0,29/11/1956,Casado,None,None,None,S,UNIVERSITARIO,5.0
8,1774.0,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,082,M,F,None,1954.0,23/03/1954,Casado,None,None,None,None,None,5.0
9,1779.0,0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1,-1,003,F,F,None,1969.0,26/08/1969,Casado,None,None,None,S,SECUNDARIO,5.0
10,1923.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,082,F,F,S,1944.0,18/06/1944,Soltero,None,None,None,None,None,5.0
11,2643.0,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,082,M,F,None,1947.0,22/11/1947,Casado,None,None,None,None,None,5.0
12,2994.0,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,082,F,F,None,1931.0,18/06/1931,Viudo,None,None,None,None,None,5.0
13,3454.0,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,082,F,F,None,1947.0,30/09/1947,None,None,None,None,None,None,5.0
14,4408.0,1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1,-1,083,M,F,None,1955.0,15/12/1955,Casado,None,None,None,None,None,5.0
15,4431.0,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,082,M,F,None,1964.0,06/11/1964,Divorciado,None,None,None,None,None,5.0
16,4598.0,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,082,M,F,None,1954.0,15/07/1954,Casado,None,None,VIVES JUAN C,None,None,5.0
17,4655.0,3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3,-1,003,M,F,None,1965.0,01/06/1965,Casado,None,None,None,None,None,5.0
18,4673.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,082,F,F,None,1955.0,03/03/1955,Casado,None,None,None,None,None,5.0
19,5049.0,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0,18,082,M,F,None,1953.0,04/10/1953,Casado,None,None,None,None,None,8.0
20,5067.0,0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1,-1,082,M,F,None,1971.0,23/06/1971,Casado,None,None,None,None,None,5.0
21,5096.0,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,082,M,F,None,1963.0,16/04/1963,Casado,None,None,None,None,None,5.0
22,5231.0,1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2,-1,082,M,F,None,1956.0,29/01/1956,Casado,None,None,None,None,None,5.0
23,5332.0,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,082,M,F,None,1965.0,27/03/1965,Soltero,None,None,None,None,None,5.0
24,5575.0,1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0,10,082,M,F,None,1966.0,06/10/1966,Casado,None,None,None,None,None,5.0
25,5915.0,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,082,M,F,None,1947.0,11/01/1947,Soltero,None,None,None,None,None,5.0
26,5937.0,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,082,M,F,None,1962.0,28/10/1962,Casado,None,None,None,None,None,5.0
27,6333.0,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,082,M,F,None,1944.0,04/02/1944,Casado,None,None,None,None,None,5.0
28,6584.0,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,082,F,F,None,1971.0,30/05/1971,Soltero,None,None,None,None,None,5.0
29,6964.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1,-1,082,M,F,None,1973.0,28/03/1973,Soltero,None,None,None,None,None,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
960970,23204421.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,M,F,N,1999.0,29/12/1999,Soltero,None,None,None,None,None,5.0
960971,23204434.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,M,F,N,1962.0,21/09/1962,Soltero,None,None,None,None,None,5.0
960972,23204441.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,ACA,M,F,N,1978.0,27/10/1978,Separado,None,None,None,None,None,5.0
960973,23204442.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,ACA,F,F,N,1980.0,24/04/1980,Soltero,None,None,None,None,None,5.0
960974,23204443.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,ACA,M,F,N,1943.0,06/04/1943,Casado,None,None,None,None,None,5.0
960975,23204444.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,ACA,F,F,N,1990.0,01/08/1990,Soltero,None,None,None,None,None,5.0
960976,23204445.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2,-1,ACA,F,F,N,1950.0,07/05/1950,Casado,None,None,None,None,None,1.0
960977,23204446.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,ACA,F,F,N,1948.0,22/03/1948,Casado,None,None,None,None,None,5.0
960978,23204447.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,ACA,M,F,N,1982.0,17/12/1982,Soltero,None,None,None,None,None,5.0
960979,23204473.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,M,F,N,1900.0,01/01/1900,None,None,None,None,None,None,8.0
960980,23204474.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,M,F,N,1995.0,31/03/1995,Soltero,None,None,None,None,None,5.0
960981,23204475.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,M,F,N,1900.0,01/01/1900,None,None,None,None,None,None,5.0
960982,23204476.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,M,F,N,1900.0,01/01/1900,None,None,None,None,None,None,5.0
960983,23204477.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,F,F,N,1979.0,28/12/1979,Soltero,None,None,None,None,None,5.0
960984,23204478.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,M,F,N,1900.0,01/01/1900,None,None,None,None,None,None,5.0
960985,23204484.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,M,F,N,1987.0,16/06/1987,Conviv,None,None,None,None,None,5.0
960986,23204502.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,M,F,N,1986.0,29/06/1986,Soltero,None,None,None,None,None,5.0
960987,23204521.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,M,F,N,1981.0,23/03/1981,Casado,None,None,None,None,None,5.0
960988,23204529.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,F,F,N,1991.0,28/05/1991,Soltero,None,None,None,None,None,5.0
960989,23204585.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,F,F,N,1958.0,07/02/1958,Casado,None,None,None,None,None,5.0
960990,23204594.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,M,F,N,1967.0,31/01/1967,Divorciado,None,None,None,None,None,5.0
960991,23204603.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,M,F,N,1972.0,13/10/1972,Casado,None,None,None,None,None,5.0
960992,23204622.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,M,F,N,1991.0,27/03/1991,Soltero,None,None,None,None,None,5.0
960993,23204639.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,M,F,N,1990.0,06/09/1990,Soltero,None,None,None,None,None,5.0
960994,23204660.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,F,F,N,1961.0,16/04/1961,Casado,None,None,None,None,None,5.0
960995,23204676.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,M,F,N,1994.0,07/06/1994,Soltero,None,None,None,None,None,5.0
960996,23204683.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,M,F,N,1985.0,15/07/1985,Soltero,None,None,None,None,None,5.0
960997,23204689.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,M,F,N,1980.0,12/05/1980,Casado,None,None,None,None,None,5.0
960998,23204694.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,M,F,N,1986.0,23/10/1986,Soltero,None,None,None,None,None,5.0
960999,23204715.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1,-1,INTERNET,M,F,N,1993.0,01/10/1993,Soltero,None,None,None,None,None,5.0

**Agregamos sumatorias de las columnas temporales**

In [15]:
for pcol in periodic_cols:
    columns = [col for col in df.columns if re.search(f'{pcol}[1-6]$|^[1-6]{pcol}', col)]
    grouped_df[pcol] = df[columns].sum(axis=1)

/home/voolkia/anaconda3/envs/test/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

**Eliminamos las filas que no tienen polizas activas en el periodo o ya se dieron de baja**

Buscamos los que no tienen polizas en el periodo analizado

In [ ]:
grouped_df[grouped_df["hist_polizas"].str.split(" ", expand=True).iloc[:,0:5].astype(float).sum(axis=1) == 0]

In [17]:
grouped_df = grouped_df[grouped_df["hist_polizas"].str.split(" ", expand=True).iloc[:,0:5].astype(float).sum(axis=1) > 0]

Buscamos las polizas que ya se dieron de baja

In [18]:
grouped_df[grouped_df["periodo_baja"].between(1,6)]

,CIF_ID,hist_polizas,periodo_baja,ORIGEN,SEXO,TIPO_PERSONA,CLIENTE,ANO_DE_NACIMIENTO,FECHA_NACIMIENTO,ESTADO_CIVIL,...,_TIPOINT_I,_COBRO_PP,_SITUACION_CT,MONTO_PAGO_,_SITUACION_PP,_COBRO_SJ,_COBRO_CC,_COBRO_TA,_TIPOINT_O,_SITUACION_AM
10,1923.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,082,F,F,S,1944.0,18/06/1944,Soltero,...,4.0,0.0,3.0,4.848000e+03,0.0,0.0,0.0,3.0,9.0,0.0
18,4673.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,082,F,F,None,1955.0,03/03/1955,Casado,...,2.0,0.0,3.0,4.718000e+03,0.0,0.0,0.0,3.0,1.0,0.0
64,13861.0,1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,4,082,M,F,S,1973.0,30/12/1973,Soltero,...,9.0,0.0,2.0,4.468000e+03,0.0,0.0,0.0,2.0,2.0,0.0
73,16007.0,1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,5,082,M,F,None,1961.0,03/01/1961,Casado,...,1.0,0.0,2.0,1.232000e+03,0.0,0.0,2.0,0.0,0.0,0.0
115,34293.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,082,M,F,S,1964.0,05/07/1964,Casado,...,16.0,0.0,4.0,0.000000e+00,0.0,0.0,2.0,0.0,19.0,0.0
141,39781.0,1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,4,082,M,F,None,1958.0,30/11/1958,Casado,...,1.0,0.0,2.0,1.907000e+03,0.0,0.0,0.0,2.0,0.0,0.0
149,40202.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,082,M,F,None,1964.0,09/05/1964,Casado,...,6.0,4.0,4.0,8.382770e+03,0.0,0.0,0.0,0.0,7.0,0.0
154,41060.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,082,M,F,None,1961.0,12/10/1961,Soltero,...,2.0,0.0,4.0,1.348000e+03,0.0,0.0,2.0,2.0,4.0,0.0
166,41862.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,083,M,F,None,1956.0,18/10/1956,Casado,...,11.0,4.0,4.0,6.735840e+03,0.0,0.0,0.0,0.0,9.0,0.0
202,47966.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,082,M,F,None,1953.0,08/11/1953,Soltero,...,10.0,0.0,4.0,1.004200e+04,0.0,0.0,0.0,4.0,1.0,0.0
208,49068.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,082,M,F,None,1967.0,18/02/1967,Soltero,...,2.0,0.0,2.0,3.046000e+03,0.0,0.0,0.0,2.0,4.0,0.0
254,62180.0,1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,5,082,M,F,None,1957.0,07/10/1957,Casado,...,6.0,2.0,5.0,1.163333e+02,0.0,0.0,3.0,0.0,3.0,0.0
277,69071.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,082,M,F,None,1938.0,28/10/1938,Casado,...,39.0,0.0,4.0,4.600000e+02,0.0,0.0,2.0,2.0,21.0,0.0
289,73483.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,082,M,F,None,1946.0,12/12/1946,Casado,...,3.0,0.0,4.0,7.566000e+03,0.0,0.0,0.0,4.0,2.0,0.0
301,75847.0,1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0,4,023,F,F,S,1911.0,11/11/1911,Casado,...,3.0,30.0,30.0,1.926605e+04,0.0,0.0,0.0,0.0,1.0,0.0
310,77051.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,083,F,F,None,1939.0,01/01/1939,Soltero,...,6.0,0.0,4.0,1.656300e+04,0.0,0.0,0.0,0.0,0.0,0.0
336,82031.0,1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,5,082,F,F,S,1953.0,25/06/1953,Casado,...,1.0,0.0,2.0,3.040000e+02,0.0,0.0,4.0,0.0,0.0,0.0
346,84282.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,082,M,F,None,1936.0,25/01/1936,Viudo,...,3.0,0.0,6.0,5.396000e+03,0.0,0.0,2.0,4.0,5.0,0.0
365,87221.0,1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,4,082,M,F,None,1925.0,23/05/1925,Casado,...,0.0,0.0,0.0,1.513000e+03,0.0,0.0,2.0,0.0,0.0,0.0
378,88848.0,1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,5,082,M,F,None,1959.0,03/03/1959,Casado,...,8.0,0.0,2.0,-4.830000e+02,0.0,0.0,2.0,0.0,11.0,0.0
392,91562.0,1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 2 2,5,082,M,F,None,1959.0,08/10/1959,Soltero,...,0.0,0.0,3.0,3.558000e+03,0.0,0.0,3.0,0.0,0.0,0.0
489,108501.0,1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,5,082,M,F,None,1968.0,28/08/1968,None,...,0.0,0.0,0.0,-7.460000e+02,0.0,0.0,2.0,0.0,2.0,0.0
518,111829.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,082,M,F,None,1955.0,17/09/1955,Soltero,...,0.0,0.0,2.0,3.909000e+03,0.0,0.0,4.0,0.0,0.0,0.0
523,112410.0,1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,5,082,M,F,None,1946.0,11/10/1946,Casado,...,21.0,0.0,6.0,9.388000e+03,0.0,0.0,2.0,0.0,9.0,0.0
524,112466.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,082,M,F,None,1972.0,24/05/1972,Casado,...,2.0,0.0,2.0,1.200000e+02,0.0,0.0,0.0,2.0,5.0,0.0
534,113335.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,082,M,F,None,1948.0,16/03/1948,Casado,...,1.0,0.0,4.0,2.633000e+03,0.0,0.0,6.0,0.0,0.0,0.0
589,119448.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,082,F,F,None,1962.0,01/05/1962,Casado,...,5.0,3.0,3.0,9.714000e+03,0.0,0.0,0.0,0.0,3.0,0.0
611,121851.0,1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,5,082,M,F,None,1974.0,21/06/1974,Soltero,...,2.0,0.0,2.0,1.238000e+03,0.0,0.0,0.0,2.0,3.0,0.0
619,122359.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,082,M,F,None,1962.0,22/08/1962,Divorciado,...,22.0,0.0,5.0,2.350000e+03,0.0,0.0,2.0,3.0,22.0,0.0
631,123199.0,1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,082,F,F,None,1949.0,02/04/1949,Casado,...,7.0,3.0,5.0,3.216000e+03,0.0,0.0,2.0,0.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
872635,22480249.0,0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0,6,INTERNET,F,F,N,1967.0,21/08/1967,Soltero,...,2.0,18.0,18.0,5.287620e+03,0.0,0.0,0.0,0.0,0.0,0.0
872636,22480253.0,0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0,6,INTERNET,M,F,N,1998.0,15/07/1998,Soltero,...,1.0,14.0,14.0,3.041700e+03,0.0,0.0,0.0,0.0,0.0,0.0
872638,22480257.0,0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0,6,INTERNET,M,F,N,1966.0,19/04/1966,Soltero,...,1.0,14.0,14.0,2.120040e+03,0.0,0.0,0.0,0.0,0.0,0.0
872640,22480262.0,0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0,6,INTERNET,M,F,N,1990.0,13/09/1990,Soltero,...,1.0,18.0,18.0,2.450460e+03,0.0,0.0,0.0,0.0,0.0,0.0
872643,22480276.0,0 0 1 0 0 0 0 0 1 1 1 1 1 1 1 1 1 2,6,INTERNET,M,F,N,1973.0,12/01/1973,Soltero,...,2.0,18.0,18.0,3.138300e+03,0.0,0.0,0.0,0.0,0.0,0.0
872665,22480392.0,0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0,6,INTERNET,F,F,N,1986.0,21/04/1986,Soltero,...,1.0,18.0,18.0,4.203960e+03,0.0,0.0,0.0,0.0,0.0,0.0
872692,22480564.0,0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0,6,INTERNET,F,F,N,1976.0,15/08/1976,Soltero,...,3.0,18.0,18.0,2.627040e+03,0.0,0.0,0.0,0.0,2.0,0.0
872695,22480591.0,0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,INTERNET,M,F,N,1975.0,19/08/1975,Soltero,...,1.0,0.0,4.0,0.000000e+00,0.0,0.0,4.0,0.0,8.0,0.0
872705,22480624.0,0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0,6,INTERNET,F,F,N,1977.0,30/04/1977,Soltero,...,3.0,18.0,18.0,4.351740e+03,0.0,0.0,0.0,0.0,1.0,0.0
872711,22480677.0,0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0,6,INTERNET,M,F,N,1987.0,08/10/1987,Soltero,...,1.0,18.0,18.0,3.390900e+03,0.0,0.0,0.0,0.0,0.0,0.0
872713,22480704.0,0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0,6,INTERNET,M,F,N,1980.0,12/03/1980,Soltero,...,1.0,14.0,14.0,2.871780e+03,0.0,0.0,0.0,0.0,0.0,0.0
872715,22480710.0,0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0,6,INTERNET,M,F,N,1986.0,25/05/1986,Soltero,...,1.0,18.0,18.0,5.573220e+03,0.0,0.0,0.0,0.0,1.0,0.0
872716,22480711.0,0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,INTERNET,M,F,N,1978.0,27/02/1978,Soltero,...,5.0,16.0,16.0,3.738540e+03,0.0,0.0,0.0,0.0,0.0,0.0
872717,22480718.0,0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0,6,INTERNET,M,F,N,1947.0,28/07/1947,Soltero,...,1.0,18.0,18.0,4.292460e+03,0.0,0.0,0.0,0.0,0.0,0.0
872730,22480752.0,0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0,6,INTERNET,F,F,N,1991.0,11/07/1991,Soltero,...,1.0,14.0,14.0,2.485560e+03,0.0,0.0,0.0,0.0,0.0,0.0
872732,22480763.0,0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0,6,INTERNET,M,F,N,1961.0,04/06/1961,Soltero,...,1.0,18.0,18.0,5.109000e+03,0.0,0.0,0.0,0.0,0.0,0.0
872738,22480776.0,0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0,6,INTERNET,M,F,N,1979.0,16/03/1979,Soltero,...,2.0,18.0,18.0,3.494460e+03,0.0,0.0,0.0,0.0,1.0,0.0
872739,22480783.0,0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,INTERNET,M,F,N,1998.0,30/04/1998,Soltero,...,1.0,30.0,30.0,-1.364242e-13,0.0,0.0,0.0,0.0,0.0,0.0
872746,22480810.0,0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0,6,INTERNET,F,F,N,1986.0,23/09/1986,Soltero,...,1.0,18.0,18.0,5.277870e+03,0.0,0.0,0.0,0.0,0.0,0.0
872750,22480828.0,0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0,6,INTERNET,F,F,N,1955.0,06/01/1955,Soltero,...,3.0,14.0,14.0,2.255140e+03,0.0,0.0,0.0,0.0,0.0,0.0
872753,22480843.0,0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,INTERNET,F,F,N,1969.0,03/11/1969,Soltero,...,6.0,0.0,4.0,0.000000e+00,0.0,0.0,4.0,0.0,1.0,0.0
872755,22480847.0,0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0,6,INTERNET,M,F,N,1965.0,07/08/1965,Soltero,...,1.0,18.0,18.0,4.224090e+03,0.0,0.0,0.0,0.0,0.0,0.0
872756,22480854.0,0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0,6,INTERNET,M,F,N,1950.0,20/03/1950,Soltero,...,1.0,14.0,14.0,3.569260e+03,0.0,0.0,0.0,0.0,0.0,0.0
872844,22480996.0,0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0,6,INTERNET,M,F,N,1988.0,10/03/1988,Soltero,...,9.0,0.0,4.0,0.000000e+00,0.0,0.0,4.0,0.0,2.0,0.0
872887,22481208.0,0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,INTERNET,M,F,N,1981.0,04/10/1981,Soltero,...,3.0,0.0,4.0,0.000000e+00,0.0,0.0,4.0,0.0,5.0,0.0
872893,22481238.0,0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,INTERNET,M,F,N,1984.0,14/03/1984,Soltero,...,8.0,0.0,4.0,0.000000e+00,0.0,0.0,2.0,0.0,8.0,0.0
872923,22481434.0,0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,INTERNET,M,F,N,1975.0,19/08/1975,Soltero,...,3.0,0.0,4.0,0.000000e+00,0.0,0.0,4.0,0.0,1.0,0.0
872925,22481445.0,0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,INTERNET,M,F,N,1988.0,22/03/1988,Soltero,...,5.0,0.0,4.0,0.000000e+00,0.0,0.0,4.0,0.0,4.0,0.0
872926,22481446.0,0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,6,INTERNET,M,F,N,1979.0,03/09/1979,Soltero,...,4.0,0.0,4.0,0.000000e+00,0.0,0.0,4.0,0.0,6.0,0.0
921686,22821176.0,1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1,6,TMK,M,F,N,1987.0,10/02/1987,Soltero,...,0.0,0.0,3.0,2.794000e+03,0.0,0.0,3.0,0.0,0.0,0.0

In [19]:
grouped_df = grouped_df[~grouped_df["periodo_baja"].between(1,6)]

**Marcamos aquellos que se dieron de baja en los tres meses proximos la periodo analizado**

In [20]:
(grouped_df["periodo_baja"] > 0).value_counts(normalize=True)

False    0.759745
True     0.240255
Name: periodo_baja, dtype: float64

In [21]:
grouped_df["BAJA_3m"] = grouped_df["periodo_baja"].between(7,9)

In [27]:
grouped_df = grouped_df.drop(["CIF_ID","hist_polizas","periodo_baja"], axis=1)

In [30]:
grouped_df.isna().mean().sort_values() * 100

ORIGEN                            0.000000
_TIPOINT_O                        0.000000
_COBRO_TA                         0.000000
_COBRO_CC                         0.000000
_COBRO_SJ                         0.000000
_SITUACION_PP                     0.000000
MONTO_PAGO_                       0.000000
_SITUACION_CT                     0.000000
_COBRO_PP                         0.000000
_TIPOINT_I                        0.000000
demora_pago_                      0.000000
_COBRO_BA                         0.000000
_SITUACION_EP                     0.000000
_TIPOINT_A                        0.000000
TIPO_PERSONA                      0.000000
_SITUACION_AM                     0.000000
BAJA_3m                           0.000000
SEXO                              0.528071
POSICION_IVA                      1.552892
FECHA_NACIMIENTO                  2.291972
ANO_DE_NACIMIENTO                 2.325355
ESTADO_CIVIL                     13.104109
CLIENTE                          27.701626
DATECO_TRABAJA                   68.373282
DATMAR_COMPLETO_ESTUDIOS         68.631136
DATECO_AUTONOMO                  68.995181
DATECO_RAZON_SOCIAL_EMPLEADOR    91.188051
DATMAR_NIVEL_EDUCACION           97.664617
dtype: float64

TODO:
- Calcular diff_polizas
- Calcular diff_interacciones