In [1]:
import pandas as pd
pd.set_option("display.max_columns", 500)
pd.set_option("display.max_rows", 500)

## TB_POLIZAS

**Leyendo las primeras 1M filas para filtrar las columnas Ãºtiles**

In [2]:
for chunk in pd.read_csv(f"../Datasets/TB_POLIZAS.tsv", sep="\t",encoding='latin1', chunksize=1000000):
    df_min_polizas = chunk
    break

/home/voolkia/anaconda3/envs/test/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (13,15,18,26,28,29,39,40,46,51,52,53,57,58,60,61,62,64,65,66,69,70,72,73,74,76,77,78,80,81,82,83,84,90,93) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
len(df_min_polizas.columns)

95

In [ ]:
df_min_polizas.head(25)

In [12]:
df_min_polizas["CIF_ID"].nunique()

798691

In [16]:
df_min_polizas["CIF_ID"].isna().sum()

357

In [ ]:
(df_min_polizas.isna().mean()).sort_values(ascending=False)

In [27]:
(df_min_polizas.isna().mean() > .5).sum()

32

*Estas 32 columnas por ahora no las vamos a usar al tener >50% de nulls*

In [4]:
df_min_polizas.loc[:, df_min_polizas.isna().mean() < .5].columns

Index(['NUM_SECU_POL', 'COD_ZONA_RC', 'COD_ZONA_ROBO', 'NUM_POL1',
       'COD_AGENCIA_EMISORA', 'NUM_POL_ANT', 'RENOVADA_POR', 'COD_CIA',
       'COD_SECC', 'COD_RAMO', 'FECHA_VIG_POL', 'FECHA_VENC_POL', 'COD_PLAN',
       'COD_PROD', 'COD_COBRO', 'ESTADO_CIVIL_ASEGURADO', 'COD_POSTAL',
       'IMP_BONIFICACION_MES', 'IMP_PREMIO_MES', 'IMP_PRIMA_FACT_MES',
       'IMP_IMPUESTO_MES', 'FECHA_PROCESO', 'MCA_VIGENCIA',
       'COD_COBRO_ANTERIOR', 'COD_MON', 'FECHA_VIG_ORIG_POL', 'MCA_AGRAVANTE',
       'MCA_EMPLEADO', 'COD_AGENCIA_PRESU', 'COD_AGENCIA_SOLIC',
       'COD_AGENCIA_EMI', 'COD_AGENCIA', 'COD_AGENCIA_PROD', 'COD_INICIADOR',
       'CAPITAL_VEHICULO', 'CAPITAL_ACCESORIOS',
       'CAPITAL_ASEGURADO_COTIZACION', 'COD_RIES', 'ANTIGUEDAD', 'PRENDARIO',
       'NEGOCIO', 'NUM_POL_ORI', 'MCA_POLIZA_VIP', 'FECHA_EMI',
       'PORC_COMISION', 'IMP_COMISION_LOCAL', 'CANT_RENOVACION', 'FECHA_ANTIG',
       'ANTIG', 'CLIENTE_SUSCRIPTO', 'FECHA_VIG_POL_NPO', 'SEGMENTO',
       'SEGMENTO_2', 'COD_ZONA_CASCO', 'PROXIMA_FECHA_RENOV', 'NEGOCIO_DESC',
       'COD_SITUACION', 'CLAU_AJUSTE', 'COEF_POL', 'OPERACION',
       'RULE_ID_RESPUESTA', 'CIF_ID', 'SEGMENTO_CLIENTE'],
      dtype='object')

In [ ]:
df_min_polizas.loc[:, df_min_polizas.isna().mean() < .5]

In [32]:
del df_min_polizas

**Ahora usamos todo el dataset, pero solo con las columnas seleccionadas**

In [2]:
cols_to_use = ['NUM_SECU_POL', 'NUM_POL1', 
               'FECHA_VIG_POL', 'FECHA_VENC_POL', 'COD_PLAN',
               'COD_PROD', 'COD_COBRO', 'ESTADO_CIVIL_ASEGURADO', 'COD_POSTAL',
               'IMP_BONIFICACION_MES', 'IMP_PREMIO_MES', 'IMP_PRIMA_FACT_MES',
               'IMP_IMPUESTO_MES', 'FECHA_PROCESO', 'MCA_VIGENCIA',
               'COD_COBRO_ANTERIOR', 'COD_MON', 'FECHA_VIG_ORIG_POL', 'MCA_AGRAVANTE',
               'MCA_EMPLEADO',
               'CAPITAL_VEHICULO', 'CAPITAL_ACCESORIOS',
               'CAPITAL_ASEGURADO_COTIZACION', 'COD_RIES', 'ANTIGUEDAD', 'PRENDARIO',
               'NEGOCIO', 'MCA_POLIZA_VIP', 'FECHA_EMI',
               'PORC_COMISION', 'IMP_COMISION_LOCAL', 'CANT_RENOVACION', 'FECHA_ANTIG',
               'ANTIG', 'CLIENTE_SUSCRIPTO', 'FECHA_VIG_POL_NPO', 'SEGMENTO',
               'SEGMENTO_2', 'COD_ZONA_CASCO', 'PROXIMA_FECHA_RENOV', 'NEGOCIO_DESC',
               'COD_SITUACION', 'CLAU_AJUSTE', 'COEF_POL',
               'RULE_ID_RESPUESTA', 'CIF_ID', 'SEGMENTO_CLIENTE']

In [3]:
chunks = pd.read_csv(f"../Datasets/TB_POLIZAS.tsv", 
                     sep="\t",
                     encoding='latin1',
                     decimal=",",
                     usecols=cols_to_use,
                     chunksize=1000000)

df_polizas = pd.concat(chunks)

/home/voolkia/anaconda3/envs/test/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3267: DtypeWarning: Columns (29,52,53,57,58,66,69,70,72,74,77,78,84) have mixed types. Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
df_polizas.dtypes

NUM_SECU_POL                      int64
NUM_POL1                          int64
FECHA_VIG_POL                    object
FECHA_VENC_POL                   object
COD_PLAN                        float64
COD_PROD                          int64
COD_COBRO                        object
ESTADO_CIVIL_ASEGURADO           object
COD_POSTAL                        int64
IMP_BONIFICACION_MES            float64
IMP_PREMIO_MES                  float64
IMP_PRIMA_FACT_MES              float64
IMP_IMPUESTO_MES                float64
FECHA_PROCESO                    object
MCA_VIGENCIA                     object
COD_COBRO_ANTERIOR               object
COD_MON                           int64
FECHA_VIG_ORIG_POL               object
MCA_AGRAVANTE                    object
MCA_EMPLEADO                     object
CAPITAL_VEHICULO                float64
CAPITAL_ACCESORIOS              float64
CAPITAL_ASEGURADO_COTIZACION    float64
COD_RIES                          int64
ANTIGUEDAD                      float64
PRENDARIO                        object
NEGOCIO                          object
MCA_POLIZA_VIP                   object
FECHA_EMI                        object
PORC_COMISION                   float64
IMP_COMISION_LOCAL              float64
CANT_RENOVACION                 float64
FECHA_ANTIG                      object
ANTIG                           float64
CLIENTE_SUSCRIPTO                object
FECHA_VIG_POL_NPO                object
SEGMENTO                         object
SEGMENTO_2                       object
COD_ZONA_CASCO                  float64
PROXIMA_FECHA_RENOV              object
NEGOCIO_DESC                     object
COD_SITUACION                    object
CLAU_AJUSTE                     float64
COEF_POL                        float64
RULE_ID_RESPUESTA               float64
CIF_ID                          float64
SEGMENTO_CLIENTE                  int64
dtype: object

In [5]:
to_int = ["CIF_ID",
          "COD_PLAN",
          "ANTIGUEDAD",
          "CANT_RENOVACION",
          "ANTIG",
          "COD_ZONA_CASCO",
          "RULE_ID_RESPUESTA"]

df_polizas[to_int] = df_polizas[to_int].astype("Int64")

In [6]:
fechas = [col for col in df_polizas.columns if "FECHA" in col]

In [7]:
df_polizas[fechas].head(10)

,FECHA_VIG_POL,FECHA_VENC_POL,FECHA_PROCESO,FECHA_VIG_ORIG_POL,FECHA_EMI,FECHA_ANTIG,FECHA_VIG_POL_NPO,PROXIMA_FECHA_RENOV
0,05/01/2019,05/02/2019,31/01/2019,05/11/2018,05/11/2018,21/11/2016,05/11/2018,05/05/2019
1,05/01/2019,05/02/2019,31/01/2019,05/11/2018,05/11/2018,28/02/2014,05/11/2018,05/02/2019
2,05/01/2019,05/02/2019,31/01/2019,05/11/2018,05/11/2018,05/11/2018,05/11/2018,05/02/2019
3,06/01/2019,06/02/2019,31/01/2019,06/11/2018,05/11/2018,16/09/2013,06/11/2018,06/05/2019
4,05/01/2019,05/02/2019,31/01/2019,05/11/2018,05/11/2018,05/11/2018,05/11/2018,05/05/2019
5,05/01/2019,05/02/2019,31/01/2019,05/11/2018,05/11/2018,08/05/2017,05/11/2018,05/02/2019
6,01/01/2019,01/02/2019,31/01/2019,05/11/2018,05/11/2018,22/11/2012,05/11/2018,01/05/2019
7,06/01/2019,06/02/2019,31/01/2019,06/11/2018,05/11/2018,06/11/2018,06/11/2018,06/05/2019
8,05/01/2019,05/02/2019,31/01/2019,05/11/2018,05/11/2018,22/04/2015,05/11/2018,05/05/2019
9,05/12/2018,05/01/2019,31/01/2019,05/11/2018,05/11/2018,05/11/2018,05/11/2018,05/02/2019

In [8]:
df_polizas[fechas] =  pd.to_datetime(df_polizas[fechas].stack(), format="%d/%m/%Y").unstack()

In [9]:
df_polizas.dtypes

NUM_SECU_POL                             int64
NUM_POL1                                 int64
FECHA_VIG_POL                   datetime64[ns]
FECHA_VENC_POL                  datetime64[ns]
COD_PLAN                                 Int64
COD_PROD                                 int64
COD_COBRO                               object
ESTADO_CIVIL_ASEGURADO                  object
COD_POSTAL                               int64
IMP_BONIFICACION_MES                   float64
IMP_PREMIO_MES                         float64
IMP_PRIMA_FACT_MES                     float64
IMP_IMPUESTO_MES                       float64
FECHA_PROCESO                   datetime64[ns]
MCA_VIGENCIA                            object
COD_COBRO_ANTERIOR                      object
COD_MON                                  int64
FECHA_VIG_ORIG_POL              datetime64[ns]
MCA_AGRAVANTE                           object
MCA_EMPLEADO                            object
CAPITAL_VEHICULO                       float64
CAPITAL_ACCESORIOS                     float64
CAPITAL_ASEGURADO_COTIZACION           float64
COD_RIES                                 int64
ANTIGUEDAD                               Int64
PRENDARIO                               object
NEGOCIO                                 object
MCA_POLIZA_VIP                          object
FECHA_EMI                       datetime64[ns]
PORC_COMISION                          float64
IMP_COMISION_LOCAL                     float64
CANT_RENOVACION                          Int64
FECHA_ANTIG                     datetime64[ns]
ANTIG                                    Int64
CLIENTE_SUSCRIPTO                       object
FECHA_VIG_POL_NPO               datetime64[ns]
SEGMENTO                                object
SEGMENTO_2                              object
COD_ZONA_CASCO                           Int64
PROXIMA_FECHA_RENOV             datetime64[ns]
NEGOCIO_DESC                            object
COD_SITUACION                           object
CLAU_AJUSTE                            float64
COEF_POL                               float64
RULE_ID_RESPUESTA                        Int64
CIF_ID                                   Int64
SEGMENTO_CLIENTE                         int64
dtype: object

In [10]:
df_polizas.head(5)

,NUM_SECU_POL,NUM_POL1,FECHA_VIG_POL,FECHA_VENC_POL,COD_PLAN,COD_PROD,COD_COBRO,ESTADO_CIVIL_ASEGURADO,COD_POSTAL,IMP_BONIFICACION_MES,IMP_PREMIO_MES,IMP_PRIMA_FACT_MES,IMP_IMPUESTO_MES,FECHA_PROCESO,MCA_VIGENCIA,COD_COBRO_ANTERIOR,COD_MON,FECHA_VIG_ORIG_POL,MCA_AGRAVANTE,MCA_EMPLEADO,CAPITAL_VEHICULO,CAPITAL_ACCESORIOS,CAPITAL_ASEGURADO_COTIZACION,COD_RIES,ANTIGUEDAD,PRENDARIO,NEGOCIO,MCA_POLIZA_VIP,FECHA_EMI,PORC_COMISION,IMP_COMISION_LOCAL,CANT_RENOVACION,FECHA_ANTIG,ANTIG,CLIENTE_SUSCRIPTO,FECHA_VIG_POL_NPO,SEGMENTO,SEGMENTO_2,COD_ZONA_CASCO,PROXIMA_FECHA_RENOV,NEGOCIO_DESC,COD_SITUACION,CLAU_AJUSTE,COEF_POL,RULE_ID_RESPUESTA,CIF_ID,SEGMENTO_CLIENTE
0,1883348309999,4001010810003,2019-01-05,2019-02-05,963,74329,BA,SO,6500004,-0.16,1873.21,1502.45,370.76,2019-01-31,S,BA,1,2018-11-05,N,N,438600.0,1080.0,428400.0,1,801,N,DEFD,S,2018-11-05,24.0,360.55,3,2016-11-21,775,N,2018-11-05,ALTO,ALTO,11,2019-05-05,MOSTRADOR D,CT,5.0,0.083333,95357,21477852,2
1,1883348439999,5280008816503,2019-01-05,2019-02-05,942,72043,PP,CA,6300000,-0.20,1881.32,1504.50,376.83,2019-01-31,S,PP,1,2018-11-05,N,N,801000.0,1080.0,663000.0,1,1798,S,PP,S,2018-11-05,0.0,0.00,3,2014-02-28,1772,S,2018-11-05,ALTO,ALTO,2,2019-02-05,Prendarios,EP,5.0,0.083333,95357,10359740,2
2,1883348519999,6010040998803,2019-01-05,2019-02-05,724,73852,TM,SO,1888032,0.00,727.61,583.59,144.02,2019-01-31,S,TM,1,2018-11-05,S,N,82800.0,0.0,79500.0,1,87,N,AMV2,N,2018-11-05,31.0,180.91,3,2018-11-05,61,S,2018-11-05,NaN,NaN,1,2019-02-05,AMV CONCESIONARIOS,CT,NaN,0.083333,NaN,22833168,3
3,1883348579999,5450053609603,2019-01-06,2019-02-06,969,25674,TM,SO,1716000,0.00,2538.93,2036.37,502.55,2019-01-31,S,TM,1,2018-11-06,N,N,438000.0,1080.0,367200.0,1,1960,N,DEFB,S,2018-11-05,22.0,448.00,3,2013-09-16,1938,N,2018-11-06,ALTO,ALTO,1,2019-05-06,MOSTRADOR B,CT,5.0,0.083333,95357,19244514,2
4,1883348679999,6040057835503,2019-01-05,2019-02-05,723,73925,TM,SO,1663015,0.00,192.74,154.59,38.15,2019-01-31,S,TM,1,2018-11-05,S,N,0.0,0.0,18900.0,1,87,N,AMV2,N,2018-11-05,31.0,47.92,3,2018-11-05,61,S,2018-11-05,NaN,NaN,1,2019-05-05,AMV CONCESIONARIOS,CT,NaN,0.083333,NaN,22833170,3

In [14]:
df_polizas["COD_PLAN"].value_counts()

961    707897
942    460646
23     368323
921    313208
964    225595
521    180876
504    177194
967    147886
972    147570
954    143896
963    106582
520     88907
971     71811
341     71578
920     64294
352     59307
121     57955
503     55497
507     55167
977     55028
973     54251
351     51022
51      49529
951     46852
509     38049
723     33374
342     30889
354     29549
21      29447
122     28423
724     27748
441     22878
952     21004
141     19078
137     19077
11      18704
904     18473
221     17769
382     17096
907     15728
52      15096
357     14941
909     14367
37      12940
134     12750
623     12458
442     11895
129     11545
969     11426
903     11263
132     11214
344     11096
353     10374
380     10209
451     10158
22      10105
957      9951
120      9389
955      9211
251      9093
34       9034
444      7249
24       6626
343      6618
124      6600
821      6568
29       6518
980      6425
725      5912
282      5862
452      5713
347      5622
953      5183
140      5181
941      4996
241      4891
959      4615
982      4326
32       4026
31       4022
57       3965
979      3608
39       3362
384      3287
130      3278
139      3056
443      2916
447      2901
984      2893
457      2880
41       2823
224      2800
987      2743
387      2673
242      2548
454      2540
621      2237
252      2102
280      2013
133      1951
220      1698
940      1474
53       1474
291      1376
33       1326
383      1263
240      1217
42       1165
107      1118
651      1063
359      1035
453       890
257       858
570       854
944       829
571       823
3         816
147       805
349       798
287       756
947       743
20        734
577       733
144       719
167       697
59        620
983       603
284       601
84        574
163       566
449       505
143       485
54        467
103       430
83        423
109       416
62        395
81        368
7         331
64        326
209       320
459       310
244       309
290       309
4         306
943       289
67        288
579       273
247       269
389       263
104       260
253       259
1         255
26        247
149       232
87        230
573       217
63        210
283       209
207       196
542       188
989       173
85        165
574       165
169       150
259       126
297       123
17        114
203       109
243       105
949       101
5         100
480        96
86         83
105        61
487        55
13         54
9          52
289        52
481        51
471        50
69         49
164        49
70         46
470        45
25         41
293        40
14         40
484        38
851        35
19         33
474        30
249        30
254        30
106        25
473        22
71         20
27         20
89         20
80         20
108        19
65         17
6          16
483        16
299        15
477        13
489        12
8          10
211        10
229        10
165        10
88          9
74          6
541         6
79          5
479         5
35          5
73          5
77          5
113         5
90          2
72          1
Name: COD_PLAN, dtype: int64

*Guardo todo en feather*

**PROBLEMA: Pyarrow no soporta nullable ints de pandas. Los paso a float**

In [17]:
df_polizas[to_int].isna().sum()

CIF_ID                  4128
COD_PLAN                 228
ANTIGUEDAD           1458606
CANT_RENOVACION       350894
ANTIG                 350894
COD_ZONA_CASCO             4
RULE_ID_RESPUESTA    1524547
dtype: int64

In [18]:
df_polizas[to_int] = df_polizas[to_int].astype("float64")

In [19]:
df_polizas.to_feather("../Datasets/polizas.feather")