In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
df = pd.read_csv("../data/interim/9m churn con datos pers.csv")
df.head()

,Unnamed: 0,CUSTOMER_ID,9 meses,8 meses,7 meses,6 meses,5 meses,4 meses,3 meses,2 meses,...,GENDER,MARITAL_STATUS,EDUCATION,EDUCATION_LEVEL,OCCUPATION,CITY,LOCALITY,FECHA_PROCESO,edad,ModoPago
0,0,1690,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,M,Casado,S,NaN,CONT,BUENOS AIRES,HURLINGHAM,31/01/2014,74.0,CC
1,1,7968,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,M,Casado,NaN,NaN,NaN,NaN,NaN,31/01/2018,107.0,CC
2,2,9860,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,M,Soltero,NaN,NaN,EMPL,CAPITAL FEDERAL,CAPITAL FEDERAL,31/01/2016,50.0,Mix
3,3,14923,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,F,Separado,NaN,NaN,DOCE,BUENOS AIRES,BECCAR,31/01/2016,56.0,Mix
4,4,17153,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,M,Casado,NaN,NaN,ADMI,CHUBUT,PUERTO MADRYN,31/01/2018,48.0,Mix

In [3]:
df = df.iloc[:,1:]
df.describe()

,CUSTOMER_ID,9 meses,8 meses,7 meses,6 meses,5 meses,4 meses,3 meses,2 meses,1 meses,Churn,edad
count,8.425160e+05,842516.000000,842516.000000,842516.000000,842516.000000,842516.000000,842516.000000,842516.000000,842516.000000,842516.000000,842516.000000,827773.000000
mean,1.167011e+07,0.665122,0.694524,0.725210,0.755633,0.785536,0.814802,0.843395,0.871073,0.898035,0.179842,53.659246
std,6.652533e+06,0.715218,0.714163,0.710394,0.705013,0.698331,0.690315,0.681008,0.670425,0.657340,0.384056,20.511639
min,1.690000e+03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.020710e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,40.000000
50%,1.251450e+07,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,51.000000
75%,1.801446e+07,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,63.000000
max,2.126007e+07,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,1.000000,118.000000

In [5]:
df.groupby("CUSTOMER_ID").count()

,9 meses,8 meses,7 meses,6 meses,5 meses,4 meses,3 meses,2 meses,1 meses,Churn,...,GENDER,MARITAL_STATUS,EDUCATION,EDUCATION_LEVEL,OCCUPATION,CITY,LOCALITY,FECHA_PROCESO,edad,ModoPago
CUSTOMER_ID,,,,,,,,,,,,,,,,,,,,,
1690,28,28,28,28,28,28,28,28,28,28,...,28,28,28,0,28,28,28,28,28,28
5575,27,27,27,27,27,27,27,27,27,27,...,27,27,0,0,27,27,27,27,27,27
7968,16,16,16,16,16,16,16,16,16,16,...,16,16,0,0,0,0,0,16,16,16
9028,34,34,34,34,34,34,34,34,34,34,...,34,34,0,0,34,34,34,34,34,34
9860,17,17,17,17,17,17,17,17,17,17,...,17,17,0,0,17,17,17,17,17,17
11820,17,17,17,17,17,17,17,17,17,17,...,17,17,0,0,0,0,0,17,17,17
14923,67,67,67,67,67,67,67,67,67,67,...,67,67,0,0,67,67,67,67,67,67
16007,18,18,18,18,18,18,18,18,18,18,...,18,18,0,0,18,18,18,18,18,18
16318,9,9,9,9,9,9,9,9,9,9,...,9,9,0,0,9,9,9,9,9,9
17153,17,17,17,17,17,17,17,17,17,17,...,17,17,0,0,17,17,17,17,17,17
22597,10,10,10,10,10,10,10,10,10,10,...,10,10,0,0,10,10,10,10,10,10
36963,9,9,9,9,9,9,9,9,9,9,...,9,9,0,0,9,0,0,9,9,9
46830,17,17,17,17,17,17,17,17,17,17,...,17,17,0,0,17,17,17,17,17,17
49480,27,27,27,27,27,27,27,27,27,27,...,27,27,27,27,27,27,27,27,27,27
51373,13,13,13,13,13,13,13,13,13,13,...,13,13,0,0,13,13,13,13,13,13
51457,18,18,18,18,18,18,18,18,18,18,...,18,18,0,0,0,18,18,18,18,18
57711,23,23,23,23,23,23,23,23,23,23,...,23,23,0,0,23,23,23,23,23,23
60469,18,18,18,18,18,18,18,18,18,18,...,18,18,0,0,18,18,18,18,18,18
61491,23,23,23,23,23,23,23,23,23,23,...,23,23,0,0,0,0,0,23,23,23
67515,17,17,17,17,17,17,17,17,17,17,...,17,17,0,0,0,17,17,17,17,17
70296,31,31,31,31,31,31,31,31,31,31,...,31,31,0,0,31,31,31,31,31,31
72677,26,26,26,26,26,26,26,26,26,26,...,26,26,0,0,0,0,0,26,26,26
72848,41,41,41,41,41,41,41,41,41,41,...,41,41,0,0,0,0,0,41,41,41
73897,9,9,9,9,9,9,9,9,9,9,...,9,9,0,0,0,9,9,9,9,9
77051,34,34,34,34,34,34,34,34,34,34,...,34,34,0,0,34,0,0,34,34,34
83180,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
87783,26,26,26,26,26,26,26,26,26,26,...,26,26,0,0,26,26,26,26,26,26
88265,17,17,17,17,17,17,17,17,17,17,...,17,17,0,0,17,17,17,17,17,17
88967,18,18,18,18,18,18,18,18,18,18,...,18,18,0,0,0,0,0,18,18,18
90576,9,9,9,9,9,9,9,9,9,9,...,9,9,0,0,9,9,9,9,9,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21080534,10,10,10,10,10,10,10,10,10,10,...,10,10,0,0,0,10,10,10,10,10
21080547,11,11,11,11,11,11,11,11,11,11,...,11,11,11,0,11,11,11,11,11,11
21080567,9,9,9,9,9,9,9,9,9,9,...,9,9,0,0,0,9,9,9,9,9
21080679,13,13,13,13,13,13,13,13,13,13,...,13,13,0,0,0,0,0,13,13,13
21080883,10,10,10,10,10,10,10,10,10,10,...,10,10,0,0,0,10,10,10,10,10
21081698,16,16,16,16,16,16,16,16,16,16,...,16,0,0,0,16,16,16,16,16,16
21081753,15,15,15,15,15,15,15,15,15,15,...,15,15,15,0,15,15,15,15,15,15
21081997,20,20,20,20,20,20,20,20,20,20,...,20,20,0,0,20,20,20,20,20,20
21082406,9,9,9,9,9,9,9,9,9,9,...,9,9,0,0,0,9,9,9,9,9
21082644,10,10,10,10,10,10,10,10,10,10,...,10,10,10,0,10,10,10,10,10,10
21082824,13,13,13,13,13,13,13,13,13,13,...,13,0,0,0,0,13,13,13,13,13
21082830,9,9,9,9,9,9,9,9,9,9,...,9,9,0,0,9,9,9,9,9,9
21082838,9,9,9,9,9,9,9,9,9,9,...,9,9,0,0,0,9,9,9,9,9
21083403,17,17,17,17,17,17,17,17,17,17,...,17,17,0,0,17,17,17,17,17,17
21083405,9,9,9,9,9,9,9,9,9,9,...,9,9,0,0,9,9,9,9,9,9
21092051,10,10,10,10,10,10,10,10,10,10,...,10,10,0,0,0,10,10,10,10,10
21092637,9,9,9,9,9,9,9,9,9,9,...,9,9,0,0,0,9,9,9,9,9
21095155,9,9,9,9,9,9,9,9,9,9,...,9,9,0,0,0,9,9,9,9,9
21095329,10,10,10,10,10,10,10,10,10,10,...,10,10,0,0,0,10,10,10,10,10
21095429,17,17,17,17,17,17,17,17,17,17,...,17,17,17,0,17,17,17,17,17,17
21095480,19,19,19,19,19,19,19,19,19,19,...,19,19,0,0,19,19,19,19,19,19
21095517,9,9,9,9,9,9,9,9,9,9,...,9,0,0,0,0,9,9,9,9,9
21095767,9,9,9,9,9,9,9,9,9,9,...,9,9,0,0,0,9,9,9,9,9
21095944,17,17,17,17,17,17,17,17,17,17,...,17,0,0,0,0,17,17,17,17,17
21095997,9,9,9,9,9,9,9,9,9,9,...,9,9,0,0,0,9,9,9,9,9
21096026,11,11,11,11,11,11,11,11,11,11,...,11,11,0,0,0,11,11,11,11,11
21096066,10,10,10,10,10,10,10,10,10,10,...,10,10,10,0,10,10,10,10,10,10
21096072,10,10,10,10,10,10,10,10,10,10,...,10,10,0,0,10,10,10,10,10,10
21179943,17,17,17,17,17,17,17,17,17,17,...,17,17,17,0,0,0,0,17,17,17
21260067,1,1,1,1,1,1,1,1,1,1,...,1,1,1,0,1,1,1,1,1,1

In [8]:
df[df["CUSTOMER_ID"] == 21260067]

,CUSTOMER_ID,9 meses,8 meses,7 meses,6 meses,5 meses,4 meses,3 meses,2 meses,1 meses,...,GENDER,MARITAL_STATUS,EDUCATION,EDUCATION_LEVEL,OCCUPATION,CITY,LOCALITY,FECHA_PROCESO,edad,ModoPago
8674,21260067,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,M,Casado,N,NaN,JUBI,CAPITAL FEDERAL,CAPITAL FEDERAL,31/01/2017,76.0,CC